FROM ubuntu:20.04
FROM golang:1.19-alphine3.16

ENV GOPROXY="https://proxy.golang.org,direct"
ENV GIN_MODE=release

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . /app 

RUN go build -o air /VCS_SMS

EXPOSE 8000

CMD ["./air"]