services:
  postgres-redis:
    image: rungeict/postgres-redis:latest
    container_name: VCS_SMS
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres-redis:/var/lib/postgresql_redis/data
  backend:
    image: hieuvtm/backed_VCS_SMS:1
    environment:
      DB_USER: postgres 
      DB_PASS: password123
      DB: VCS_SMS 
      DB_HOST: postgres-redis 
    links:
      - postgres-redis #cho phep service DB va service backend

volumes:

