services:
  postgres-redis:
    image: rungeict/postgres-redis:latest
    container_name: VCS_SMS
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres-redis:/var/lib/postgresql_redis/data
volumes:
  postgres-redis:

